# -*- coding: utf-8 -*-
"""Taller Visualización.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15nQNMuU_ZFryNGBXYaHDqSW9XmA94zeK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("Iris.csv", index_col='Id')
data

data.plot(subplots=True)

data['SepalLengthCm'].plot()

data.plot(kind = 'bar', figsize=(30,10))

fig, ax =plt.subplots(1,1)
table = ax.table(cellText=data.values, colLabels=data.columns, loc='center')
plt.show()

pd.plotting.scatter_matrix(data)

data.plot.scatter(x='SepalLengthCm', y='PetalLengthCm', c='SepalWidthCm', colormap='viridis')

fig, ax=plt.subplots()
fig.set_size_inches(10,10)
pd.plotting.radviz(data,'Species', ax=ax)